spring.application.name=journeyorchestrator

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/journey-orchestrator
spring.data.mongodb.database=journey-orchestrator
spring.data.mongodb.auto-index-creation=true

# Custom MongoDB Properties
journey-orchestrator.persistence.mongodb.connection-timeout=5000
journey-orchestrator.persistence.mongodb.max-pool-size=20
journey-orchestrator.persistence.mongodb.min-pool-size=5
